### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by filipafcastro** [HaydenFaulkner/Tennis#1]
Hi :) Thanks for sharing this dataset! Would it also be possible to share the models ?

**Comment by HaydenFaulkner** [comment]
Hi @filipafcastro 

It's probably a bit late now but I have finally gotten around to finishing up this repo, with the best models (0006 - framewise, 0042 - CNNRNN, and 0102 - captioning) now available in the models directory. Metric results and a 3D CNN model to be uploaded within the next week or two.

Thanks for taking an interest in my work and sincerest apologies for only getting models available now. 

Hayden
